branches:
  except:
    - master
before_install:
  - date
  - uname -a
  - ulimit -a
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - cat /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install make locales autoconf libreadline-dev libwww-perl libconfig-yaml-perl graphviz haskell-platform drift pandoc po4a libghc-temporary-dev libghc-haskeline-dev libghc-utf8-string-dev libghc-hssyck-dev libgc-dev gcc-multilib
  - git --version
  - ghc --version
  - git fetch --tags
script:
  - autoreconf -i
  - ./configure
  - make
  - make regress
  - make selftest
  - make install
after_script:
  - date
