language: objective-c

branches:
  except:
    - master
before_install:
  - date
  - export PATH="$HOME/Library/Haskell/bin:$PATH"
  - ./travis-ci/setup_osx.sh
  - git fetch --tags
  - ./travis-ci/show_setting_osx.sh
script:
  - ./travis-ci/build.sh
after_script:
  - date
