before_install:
  - date
  - uname -a
  - cat /proc/cpuinfo
  - sudo apt-get -qq -y install make locales autoconf libreadline-dev libwww-perl libconfig-yaml-perl graphviz haskell-platform drift pandoc libghc-readline-dev libghc-utf8-string-dev libghc-hssyck-dev libghc-pandoc-dev
  - sudo apt-get -qq -y install pbuilder debootstrap devscripts debian-archive-keyring
script:
  - ghc --version
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - make regress
  - cp dot.pbuilderrc ~/.pbuilderrc
  - sudo DIST=sid ARCH=amd64 pbuilder create --override-config --configfile ~/.pbuilderrc
after_script:
  - date
