branches:
  except:
    - master
before_install:
  - date
  - uname -a
  - cat /proc/cpuinfo
  - sudo apt-get -qq -y install make locales autoconf libreadline-dev libwww-perl libconfig-yaml-perl graphviz haskell-platform drift pandoc po4a libghc-readline-dev libghc-utf8-string-dev libghc-hssyck-dev libgc-dev gcc-multilib wine
  - cabal update
  - git --version
  - ghc --version
  - git fetch --tags
script:
  - autoreconf -i
  - ./configure
  - make cabal-install
  - make distclean
  - autoreconf -i
  - ./configure
  - make
  - make manual_ja.html
  - sudo make install
  - make regress
after_script:
  - date
