language: objective-c

branches:
  except:
    - master
before_install:
  - date
  - export PATH="$HOME/Library/Haskell/bin:$PATH"
  - ./travis-ci/setup.sh
  - ./travis-ci/show_setting.sh
script:
  - ./travis-ci/build.sh
after_script:
  - date
