language: objective-c

branches:
  except:
    - master
before_install:
  - date
  - uname -a
  - ulimit -a
  - brew update --verbose
  - brew install ghc --verbose
  - export GHC=/usr/local/bin/ghc
  - brew install haskell-platform --verbose
  - cabal update || cabal update
  - export HSPACKS="derive temporary haskeline utf8-string HsSyck test-framework-th test-framework-hunit test-framework-quickcheck2 uniplate"
  - cabal install $HSPACKS || cabal install $HSPACKS
  - git --version
  - $GHC --version
  - git fetch --tags
script:
  - autoreconf -i
  - ./configure
  - make install
  - make regress
  - make selftest
  - make rtstest
after_script:
  - date
